### ISSUE TITLE
install

### ISSUE THREAD

**Issue by ZHENFENG13** [ted-wq-x/my-blog-project#5]
感觉第一步install站点作用不是太大

**Comment by ted-wq-x** [comment]
这个是根据原有的框架改动的，我fork的版本的功能基本都实现了。

**Comment by ted-wq-x** [comment]
还是需要安装的，有不少的参数是需要设置的

**Comment by ZHENFENG13** [comment]
嗯，因为我的想法是当作个人博客模板来用，配置文件就不是特别需要动态化了，docker化后也会特别方便。

**Comment by ZHENFENG13** [comment]
如果继续开源的话，可能留下来也好，都是个人看法
